[package]
name = "chat-engine"
version.workspace = true
edition.workspace = true

[dependencies]
chat-core = { path = "../chat-core" }
chat-server = { path = "../chat-server" }
chat-twitch = { path = "../chat-twitch" }
chat-youtube = { path = "../chat-youtube" }
anyhow.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true

[dev-dependencies]
reqwest.workspace = true
tracing-subscriber.workspace = true
webbrowser.workspace = true
